#!/bin/bash

echo "Updating submodules..."
git submodule update --init --recursive

echo "Downlading gnomeshell-extension-manage..."
wget -N https://raw.githubusercontent.com/NicolasBernaerts/ubuntu-scripts/master/ubuntugnome/gnomeshell-extension-manage -O gnomeshell-extension-manage
echo "Downlading atom..."
wget -N https://atom.io/download/deb -O atom.deb
echo "Downlading google chrome..."
wget -N https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb

echo "Installing system develoment packages..."
sudo apt-get update
sudo apt-get -y install build-essential cmake curl fish git python-dev python-pip

echo "Installing python develoment packages..."
sudo pip install pip --upgrade
sudo pip install conan autopep8 jedi

echo "Installing atom..."
sudo dpkg -i atom.deb

echo "Installing google chrome..."
sudo apt-get install libappindicator1 libindicator7 libpango1.0-0 libpangox-1.0-0
sudo dpkg -i google-chrome-stable_current_amd64.deb

echo "Installing user themes and setting up gnome shell extensions..."
sudo Flat-Plat/install.sh
sudo rm -rf '/usr/share/icons/Flat Remix'
sudo cp -r 'Flat-Remix/Flat Remix' /usr/share/icons
./gnomeshell-extension-manage --install --extension-id 307

echo "Installing ycmd..."
sudo apt-get -y install golang-go mono-complete mono-xbuild nodejs npm rustc cargo
sudo ln -s /usr/bin/nodejs /usr/bin/node
./ycmd/build.py --clang-completer --gocode-completer --tern-completer #--racer-completer

echo "Install oh-my-fish..."
oh-my-fish/bin/install --offline -y
