#!/bin/bash
pushd `dirname $0` > /dev/null
DOTFILE_PATH=`pwd -P`
popd > /dev/null

# Install system packages from the standard repository
sudo pacman -Syu --needed cups fish gnome gnome-tweak-tool hplip multilib-devel networkmanager ntfs-3g wireless_tools wpa_supplicant yaourt 

# Install system packages from the AUR
yaourt -S --noconfirm --needed chrome-gnome-shell-git google-chrome materia-theme nerd-fonts-complete paper-icon-theme-git

# Install development packages from the standard repository
sudo pacman -Syu --needed atom clang clang-tools-extra cloc cmake docker gdb git gvim meld ninja nodejs npm openssh python-pip tmux valgrind vim-runtime

# Install content creation packages from the standard repository
sudo pacman -Syu --needed blender gimp 

# Install content creation packages from the AUR
yaourt -S --noconfirm --needed substance-designer substance-painter

dconf load / < $DOTFILE_PATH/database.dconf

GTK_THEME=$(gsettings get org.gnome.desktop.interface gtk-theme | sed "s/'//g")
sudo cp -v --backup /usr/share{/themes/$GTK_THEME,}/gnome-shell/gnome-shell-theme.gresource
